[package]
name = "kaibun-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kakasi = "0.1.0"
text_io = "0.1.12"
wana_kana = "3.0.0"
